import {
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiExpress,
  SiPrisma,
  SiPostgresql,
  SiGit,
  SiGithub,
  SiDocker,
  SiGreensock,
} from "react-icons/si";

export const skills = [
  {
    name: "React",
    icon: SiReact,
    color: "#61DAFB",
    description: "JavaScript library for building interactive user interfaces.",
    tags: ["Hooks", "JSX", "Context"],
  },
  {
    name: "Next.js",
    icon: SiNextdotjs,
    color: "#ffffff",
    description: "Full-stack React framework for production applications.",
    tags: ["SSR", "App Router", "SEO"],
  },
  {
    name: "Tailwind CSS",
    icon: SiTailwindcss,
    color: "#38BDF8",
    description: "Utility-first CSS framework for building modern UIs.",
    tags: ["Responsive", "Utility", "Dark Mode"],
  },
  {
    name: "TypeScript",
    icon: SiTypescript,
    color: "#3178C6",
    description: "Strongly typed JavaScript for scalable applications.",
    tags: ["Types", "Safety", "DX"],
  },
  {
    name: "JavaScript",
    icon: SiJavascript,
    color: "#F7DF1E",
    description: "The language behind the modern web.",
    tags: ["ES6+", "DOM", "Async"],
  },
  {
    name: "Node.js",
    icon: SiNodedotjs,
    color: "#83CD29",
    description: "Backend JavaScript runtime.",
    tags: ["Runtime", "API", "Backend"],
  },
  {
    name: "Express",
    icon: SiExpress,
    color: "#ffffff",
    description: "Minimal backend framework for Node.js.",
    tags: ["REST", "Middleware", "Routing"],
  },
  {
    name: "Prisma",
    icon: SiPrisma,
    color: "#8B5CF6",
    description: "Modern TypeScript ORM.",
    tags: ["ORM", "Studio", "Migration"],
  },
  {
    name: "PostgreSQL",
    icon: SiPostgresql,
    color: "#336791",
    description: "Powerful relational database.",
    tags: ["SQL", "Database", "Performance"],
  },
  {
    name: "Git",
    icon: SiGit,
    color: "#F05032",
    description: "Version control system.",
    tags: ["Commit", "Branch", "Merge"],
  },
  {
    name: "GitHub",
    icon: SiGithub,
    color: "#ffffff",
    description: "Code hosting and collaboration.",
    tags: ["Repo", "Actions", "PR"],
  },
  {
    name: "Docker",
    icon: SiDocker,
    color: "#2496ED",
    description: "Containerized application deployment.",
    tags: ["Container", "Compose", "Deploy"],
  },
  {
    name: "GSAP",
    icon: SiGreensock,
    color: "#88CE02",
    description: "Professional animation library.",
    tags: ["Timeline", "ScrollTrigger", "Motion"],
  },
];
